version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/app_patch
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user

  Afterinstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user